import * as QueryKitNest from './index';

describe('public API', () => {
  it('exports the main helpers from the package root', () => {
    for (const name of [
      'AggregateDTO',
      'ApiErrorResponses',
      'ApiFieldsQuery',
      'ApiPaginatedResponse',
      'ApiParamId',
      'ApiPropertyCreatedAt',
      'ApiPropertyId',
      'ApiPropertyUpdatedAt',
      'ApiResourceQuery',
      'CHECK_POLICIES_KEY',
      'CheckPolicies',
      'CountDTO',
      'EmptyStringToNullPipe',
      'Fields',
      'FieldsBadRequestException',
      'FieldsExceptionFilter',
      'FieldsParser',
      'FieldsProjector',
      'FieldsQuery',
      'FieldsValidator',
      'FindByIdDTO',
      'FindManyDTO',
      'FindOneDTO',
      'FindUniqueDTO',
      'PageMetaDTO',
      'PageOptionsDTO',
      'PaginatedDTO',
      'PoliciesGuard',
      'QueryDTO',
      'QueryService',
      'QueryTransformPipe',
      'ResourceQuery',
      'ValidationUtil',
      'buildFieldSchemaFromDto',
      'createCaslAccessibleWhere',
      'diffObjects',
      'filterCaslFields',
      'getDtoFields',
      'hasObjectDifferences',
      'isBoolean',
      'isNumber',
      'isObject',
      'isPlainObject',
      'parseBoolean',
      'parseObject',
      'parseObjectProperties',
      'parseQueryObject',
      'prepareFieldsQuery',
      'relation',
      'serializeDecimalValues',
    ] as const) {
      expect(QueryKitNest[name]).toBeDefined();
    }
  });
});
